[dmenu]
dmenu_command = rofi -dmenu -i -p "Network" -theme ~/.config/rofi/network.rasi
rofi_highlight = True
compact = False
wifi_icons = 󰤠󰤢󰤥󰤨

[editor]
terminal = ghostty
gui_if_available = True

[dmenu_passphrase]
; TODO: Make new config for this vibe it based on network config
obscure = True
show_pass = --wait-after-command=true -e "nmcli device wifi show-password"
; TODO: Fix this guy
